import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "@/components/providers/convex-client-provider";
import { Header } from "@/components/header";
import { SidebarWrapper } from "@/components/sidebar-wrapper";
import { ResponsiveMain } from "@/components/responsive-main";
import { AuthGate } from "@/components/auth-gate";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ConvexClientProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <div className="flex flex-col h-screen">
              <Header />
              <AuthGate>
                <div className="flex flex-1 overflow-hidden">
                  <SidebarWrapper />
                  <ResponsiveMain>
                    {children}
                  </ResponsiveMain>
                </div>
              </AuthGate>
            </div>
          </body>
        </html>
      </ConvexClientProvider>
    </ClerkProvider>
  );
}
